# apply: kubectl apply -f k8s-rws.yaml
# check: kubectl get all

apiVersion: v1
kind: Service
metadata:
  name: rws-service
spec:
  selector:
    app: rws
  ports:
      # targetPort is Pod/container's port. port is where other pods (in same cluster) connect to.
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rws
  labels:
    app: rws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rws
  template:
    metadata:
      labels:
        app: rws
    spec:
      containers:
      - name: rws
        image: bastienbng/rustwebservice
        ports:
        - containerPort: 8000

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-example-ingress
spec:
  tls:
  - hosts:
      - smartnotary.fr
    secretName: testsecret-tls
  rules:
  - host: smartnotary.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rws-service
            port:
              number: 8000

---
apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lVZUlYWGpUMDRQSHBsN3dNSjJpUzI0MzBYNkxvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF3d09jMjFoY25SdWIzUmhjbmt1Wm5Jd0hoY05Nakl3TXpBM01UazFOalEyV2hjTgpNak13TXpBM01UazFOalEyV2pBWk1SY3dGUVlEVlFRRERBNXpiV0Z5ZEc1dmRHRnllUzVtY2pDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU10OHRZZlQwaWU4NVVQaFpjVjlVYjlpcGV0Q0t1YXgKMVBKZTN5MC9RVjhJMGpHMjkvQVBQa2JhUUhObk9VeFRJU1pBOU0wWTJ1RkNsaEdpZjlVa1o3ditpY2wrSnFPNgo5ZUVtd0pxT1RvOTBqSmJYU1NtZkpaTlpzYnQwdE1DOGpUMjVhcnpQSkIzSlZPTEpFQStIeEdaRmdNbUlxVElnCjMyaG5pRTUrZW1GSEV3WFkvRTEyT3RoRFNYeGxOWFNudHE1ek51MHlTa0NOZ1VIaFUwYkJtdE5MSG5KVnRMUWwKek1jTXlQVitJZ3ZSNHg4SURjS0pQalhjNWpVT1prNzBBYUdOalRFYXdWUllRdGthRUMwN3hYR1lMVVBKNlV2VAptWGRIUENweWM1cnhFZlJmUE9PSndsS3dJRGlVSTA5TGhqUjhkaVRGRVFsNk12cEsrcTJQUzdVQ0F3RUFBYU5UCk1GRXdIUVlEVlIwT0JCWUVGSXZNeUJyTEl6UVZxU2UxdDJsY1ZvdWc0eEEyTUI4R0ExVWRJd1FZTUJhQUZJdk0KeUJyTEl6UVZxU2UxdDJsY1ZvdWc0eEEyTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFBTFRRYlhpRkR1RzNDVy8xMG5BczVrOEpUR2gydThHVlVZTThKT3g4Zms0TlhYOUc0bzN2cVM3Ckp0UDVnYWZtZTdTN0JzV1hWbldNcE1FaG9XbHNyVGthSTBITi80OThsVlJxSWRqdVlzeDZOZS8vUU5SNmpoQTYKRmlQZFV0RWhjZ0FBekpVb0IvczFFcHg2enlhUUVrWm9KeGU3NVkwSm9URGtWbUdITkMrd3k1aFdNQTVLMW11Sgp3dDRHSG9PRGVoblR1Nk9uUmtNYy9GS2RmcDdEWlZyVUVCVUprQWRsdk5NcW5IWDYvbTlYTnJySnVJa20yL2R4Cm5BWnoyYWtLRHE2YnpRYTZrRHdsemJ6Qm1vR09vYVQ2LzZLZjdIY3VvaXFobVVDd09TUHBWaGo2a1pWWlBrb2YKdlB1aXpYOUN0cDNmcW5zN2ZpTVlXcFR2N2pYLzEvZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeTN5MWg5UFNKN3psUStGbHhYMVJ2MktsNjBJcTVySFU4bDdmTFQ5Qlh3alNNYmIzCjhBOCtSdHBBYzJjNVRGTWhKa0QwelJqYTRVS1dFYUovMVNSbnUvNkp5WDRtbzdyMTRTYkFtbzVPajNTTWx0ZEoKS1o4bGsxbXh1M1Mwd0x5TlBibHF2TThrSGNsVTRza1FENGZFWmtXQXlZaXBNaURmYUdlSVRuNTZZVWNUQmRqOApUWFk2MkVOSmZHVTFkS2Uycm5NMjdUSktRSTJCUWVGVFJzR2EwMHNlY2xXMHRDWE14d3pJOVg0aUM5SGpId2dOCndvaytOZHptTlE1bVR2UUJvWTJOTVJyQlZGaEMyUm9RTFR2RmNaZ3RROG5wUzlPWmQwYzhLbkp6bXZFUjlGODgKNDRuQ1VyQWdPSlFqVDB1R05IeDJKTVVSQ1hveStrcjZyWTlMdFFJREFRQUJBb0lCQUg3NE1Oa3cvYmZYOFFKNwpHU0t5Z0ppMytDbWtudHBWNmpiVnBkSTQzeFJxajZWL3NwTnpIM3ZjWVV6aEF1cXlFRVFyVWRUTUJuOTZLZU9WCkRzaXpMNXNwUjFhWHhZcHlkVXZvLzFNeEtxbnVvbTdZcElrNUNadzQ0bUxDZnFxb3ZFVGdkazZidmNCc1NQQTkKWHkwaG5SWG5sbVdxUlZESEhEK3NJbXhBRlNLdXRzVEdycS9xR25QdDVCR0dhNFhPUlpLbG9KTXZsUzRNOTc2Nwo1amlpa0sxRmFhUVFoTjVQUVJZa2hneHdIR2hjcTBTZUxObVgyTHN6M0ZocExGSzdEeEtITzRmN2RVQ2w0V28wCklDTEJFM0Q3T05Pbml3NHZkZ3plQXZuckY1SFdQN0xaNFRldU1DR3lDT1IxUmxuaVdvMDBTdVFGZDI4SW5sTVkKRUR5VnJhRUNnWUVBNWFrajQzdktDekdmZDc2a09OSjVQS3NmUTA0WlNZbTFyMlFSRHBqZTN1Zk5xUnFmamxwSApvU2Nua3pCYmxzMy9QbksyZGVKenE4dFh1b1g1OVpNejl6Z2RzZ0dteXlkdW93REtWY2VmV1FPUWNVdnNLT01uCkZ5NDBQSk5IYkZLSE9IdUxUTjVGWTltM1pQQllWRk9tZHVUYlFOMy9vbkd6VXZGb2h3RnpiTGtDZ1lFQTR0TWMKVzFGZE1TODYzY3U4ZGR5VnFXcUNDY1BlakhPTFp2NVdkUEU5cms0TS9NbEQyREZwMVhtVnlwdUZxY3QxMU16UQpGMHcyaVUwR1Jhc2dXdkxJRXVRTVQ4NVlIVmErSUxyeWtUNHJrYWk2Yytua0c0amQ5cDRRRnA5VEluOGZjdzlpCkRwK1Y4TzU4NEJPbkgyMFRibTZSblA2QU1ua0FUZWowZGVKbDhOMENnWUI1NEMrK2VpUDNtc2J3eWdmbWE3T1IKQVpMZXFlUjdoUXdZM3JhNmsxKzYxVExyNmNnQXlHSTQ0RWw5TCsxNjh5amdJQW82TndtQmdyQzB1SUswMHdDQgowcExYczA2cmd1cVFzRXV3Qi9iRlMwSHREZ2h1amxWaFZOQzkwTDdYZWxodUhnb0hxZkVURXlmaTlqVTUwd2FGCkUrQlM1VHpUSFJtNEM0cVlFcW9KYVFLQmdRRGN4bGpxZFVaODhoaWMrNG9qT2lJZDlVSS9HUHZMdjBjbloxVmwKbTgzS2s4UEdaR3Y1eVJiWEp2SHFjL2ZrcmRteDEreVBVS29nZCswcjhJV2NvSVNuQm5zSlRyR3JWTnZZWmI1bQpLcG9qdTVSSDhKY0xTZXVwK0cxMlozdDJyejlBTWUvaWhlaGV5dktXOCtvT0I1QUxRK25OWWxZTFNvVkdVQUZwCm9JUlNyUUtCZ1FDdzZlZ2ZTaVU1L21UTmgwUGpZV1RqNm9UMFF0UmRvdXhBUlBTWFI2YitNeVVKeU8yTmtOOTYKV0lubjNiTzdTSnlHSDdmcCsycjFKZFBuZ2ltSXNjRU5ZZmtWKzJvMk9aL3g0RFk1QkdHZTlTOHNHRkh2MVMvUwoyVlhxQ1l1b1NnL2IwbHErYllwL0k0UWdZY3IyNTFCQ1RubDIyMmMxZHN3NlA0Y0RRbXNvVXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls