[package]
name = "client_side"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
sha2 = "0.10.2"
hex-literal = "0.3.4"
wasm-bindgen = "0.2.67"